### PR TITLE
Add method for listing bucket objects

### PR DESCRIPTION
**Pull request by gregfletch**
*Related Issue(s) or Task(s)*

*Why?*

Dean requested the ability to be able to list objects within an S3 bucket.

*How?*

Add a `list` method that wraps the AWS SDK `list_obects_v2` method.

And update rubocop config to ensure string literals are consistent.

*Risks*

Low, new method

*Requested Reviewers*

@bcarr092 @deankeo

### CODE REVIEW

**Comment by deankeo** [comment]
This is good. However, I think we'll need to be able to list files based on metadata as well, if possible, since the Cloud::FileStorageService generates a random filename when storing the file on S3, and we don't really know what it is.

**Comment by gregfletch** [comment]
I don't believe you can search based on metadata. But again, as discussed earlier if you are writing to directories within the bucket, you could pass the parent directory/directories as the prefix.

**Comment by bcarr092** [comment]
Can we restrict this functionality? 

This would essentially allow an attacker to list all items in a bucket if they had access as opposed to having to know what they are looking for. I see your comment above regarding not being able to search by metadata but can we lock this down by directory or some other least privilege construct? This should be done in IAM in AWS.

**Comment by gregfletch** [comment]
I don't know if AWS has that granular of policy (I think the level of policy is just allowing you to be able to perform a list on a bucket you have access to). I will work with Farzad to look into the policy settings available.

**Pull request closed without merging**
